# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Rune.destroy_all

Rune.create(name: "ANSUZ", symbol: "https://symbolikon.com/wp-content/uploads/edd/2019/09/NordicRunes-ansuz-bold-400w.png", description: "Be ready for the unexpected. Changes! ANSUZ urges you to explore your depths as well as to practice your sensibility and power of observation.")
Rune.create(name: "HAGALAZ", symbol: "https://symbolikon.com/wp-content/uploads/edd/2019/09/NordicRunes-hagalaz-bold-400w.png", description: "Wish of change and freedom. But for that it is necessary to put the material reality aside. Look at your inner world. If things seeem to be out of control a break-up might a good idea. Self growth cycle.")
Rune.create(name: "KANO", symbol: "https://symbolikon.com/wp-content/uploads/edd/2019/09/NordicRunes-kaunan-bold-400w.png", description: "This is the RUNE of fire. It means the end of darkness in your life. Your passion and sensuality may be a sign of a coming marriage.")
Rune.create(name: "EIWAZ", symbol: "https://symbolikon.com/wp-content/uploads/edd/2019/09/NordicRunes-eiwaz-bold-400w.png", description: "It means things will turn out fine, no matter how difficult they are. The obstacles are instruments to test your patience. Hold your anxiety.")
Rune.create(name: "OTHILA", symbol: "https://symbolikon.com/wp-content/uploads/edd/2019/09/NordicRunes-othala-bold-400w.png", description: "It means radical break up ahead but you will reach your dreams: your role in society, material goods, and your beliefs. To find out how you really are you may need to put away some of your claims.")
Rune.create(name: "MANAZ", symbol: "https://symbolikon.com/wp-content/uploads/edd/2019/09/NordicRunes-mannaz-bold-400w.png", description: "The start up: the need to improve your 'self', to help your relationship with the world. Keep your modesty. Your path will be found.")
Rune.create(name: "PERTH", symbol: "https://symbolikon.com/wp-content/uploads/edd/2019/09/NordicRunes-pertho-bold-400w.png", description: "Mysterious powers are taking place but tend to be revealed. It is a perfect time for reflection and also material gains.")
Rune.create(name: "BERKANA", symbol: "https://symbolikon.com/wp-content/uploads/edd/2019/09/NordicRunes-berkanan-bold-400w.png", description: "Fertility. The birth of a person or a new idea. Take your steps carefully.")
Rune.create(name: "GEBO", symbol: "https://symbolikon.com/wp-content/uploads/edd/2019/09/NordicRunes-gebo-bold-400w.png", description: "It is union, partnership of any sort. But you must keep your individuality and self confidence. For this is the RUNE of freedom. In any position it has the same meaning.")
Rune.create(name: "RAIDO", symbol: "https://symbolikon.com/wp-content/uploads/edd/2019/09/NordicRunes-raidho-bold-400w-1.png", description: "This is the moment to act. Find out what your heart wishes. Resistances will be gone. RAIDO is union and reunion. The end of conflicts.")
Rune.create(name: "THURISAZ", symbol: "https://symbolikon.com/wp-content/uploads/edd/2019/09/NordicRunes-thurisaz-bold1-400w.png", description: "The door is it's symbol. Then observe every moment, every detail. Think it all over and get free from your ghosts. Then cross the borders.")
Rune.create(name: "DAGAZ", symbol: "https://symbolikon.com/wp-content/uploads/edd/2019/09/NordicRunes-dagaz-bold-400w.png", description: "A big turn over in your life. Might be a new love, new work, new opportunities, or a new life attitude. DAGAZ claims darkness is gone and the sun will light your way.")
Rune.create(name: "SOWELU", symbol: "https://symbolikon.com/wp-content/uploads/edd/2019/09/NordicRunes-sowilo-bold-400w.png", description: "It is a victory and success. To some however, it can be a trip to the inner world in search of balance. It is time to admit something long denied.")
Rune.create(name: "LAGUZ", symbol: "https://symbolikon.com/wp-content/uploads/edd/2019/09/NordicRunes-laguz-bold-400w.png", description: "You urge to follow your instincts but you forget the negative consequences. This is the RUNE of the supernatural power inside your mind that will give you protection.")
Rune.create(name: "ISA", symbol: "https://symbolikon.com/wp-content/uploads/edd/2019/09/NordicRunes-isa-bold-400w.png", description: "All your plans will stay frozen and suspended although you do not realize that. Do not overwork. Try to find out what keeps you attached to your situation and throw away what is old. Resignation might mean wisdom. Warning: do not count on your friends help.")
Rune.create(name: "ALGIZ", symbol: "https://symbolikon.com/wp-content/uploads/edd/2019/09/NordicRunes-tiwaz-bold-400w.png", description: "This is the RUNE of action, victory, new opportunities, and challenges. Be strong and take control of your emotions. Problems should not be ignored.")
Rune.create(name: "EHWAZ", symbol: "https://symbolikon.com/wp-content/uploads/edd/2019/09/NordicRunes-tiwaz-bold-400w.png", description: "Changes! It can even be a home moving to another country. Your decisions tend to be right.")
Rune.create(name: "TEIWAZ", symbol: "https://symbolikon.com/wp-content/uploads/edd/2019/09/NordicRunes-tiwaz-bold-400w.png", description: "Victory at any competition. If the question is love, you and your partner have a lot to work out together.")
Rune.create(name: "WUNJO", symbol: "https://symbolikon.com/wp-content/uploads/edd/2019/09/NordicRunes-wunjo-bold-400w.png", description: "Comprehension has become wisdom and a deep and lasting affection is about to come. Joy at work.")
Rune.create(name: "JERA", symbol: "https://symbolikon.com/wp-content/uploads/edd/2019/09/NordicRunes-jera-bold-400w.png", description: "It invites you to optimism, but nothing comes fast, since each happening has its own cycle. Keep your trust and perseverance.")
Rune.create(name: "NAUTIZ", symbol: "https://symbolikon.com/wp-content/uploads/edd/2019/09/NordicRunes-naudhiz-bold-400w.png", description: "Your dark sides block you and make you weak. Investigate what makes you so attractive to bad luck.")
Rune.create(name: "INGUZ", symbol: "https://symbolikon.com/wp-content/uploads/edd/2019/09/NordicRunes-ingwaz-bold-400w.png", description: "Claims you to split up relationships or old habits. You are ready for a new start. Even for a new child. The meantime could be dangerous. So keep your good mood.")
Rune.create(name: "FEHU", symbol: "https://symbolikon.com/wp-content/uploads/edd/2019/09/NordicRunes-fehu-bold-400w.png", description: "Great luck: wealth, goals, and love to come true. This is a conquest a not a present. Share your luck!")
Rune.create(name: "URUZ", symbol: "https://symbolikon.com/wp-content/uploads/edd/2019/09/NordicRunes-uruz-bold-400w.png", description: "You may lose someone or something. You will rise from the remainings of old values.")
Rune.create(name: "The Plain RUNE", symbol: "https://www.transparentpng.com/thumb/pebble-stone/oz-pebble-queensland-based-wholesaler-decorative-pebble-png-2.png", description: "This RUNE is destiny. It guides your karma, the whole of all your previous existences. Your obstacles are your passport to a new start. Cheer up! This RUNE links you to your real fate. Good Luck!")
